<?php

declare(strict_types=1);

/**
 * Скрипт для создания бэкапа базы данных
 * 
 * Использование:
 * php scripts/backup_db.php
 * 
 * Создает SQL дамп в storage/backups/
 */

$baseDir = dirname(__DIR__);
require $baseDir . '/src/bootstrap.php';

$backupDir = $baseDir . '/storage/backups';
if (!is_dir($backupDir)) {
    mkdir($backupDir, 0775, true);
}

$pdo = Logush\Database::connectFromEnv();
if (!$pdo) {
    fwrite(STDERR, "Ошибка подключения к БД\n");
    exit(1);
}

$timestamp = date('Y-m-d_H-i-s');
$backupFile = $backupDir . "/backup_$timestamp.sql";

fwrite(STDOUT, "Создание бэкапа БД...\n");

$fp = fopen($backupFile, 'w');
if (!$fp) {
    fwrite(STDERR, "Ошибка создания файла бэкапа\n");
    exit(1);
}

fwrite($fp, "-- Database backup created at " . date('Y-m-d H:i:s') . "\n");
fwrite($fp, "-- Generated by backup_db.php\n\n");
fwrite($fp, "SET FOREIGN_KEY_CHECKS = 0;\n");
fwrite($fp, "SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n");
fwrite($fp, "SET time_zone = '+00:00';\n\n");

$tables = [
    'products',
    'categories',
    'colors',
    'sizes',
    'orders',
    'quotes',
    'users',
    'settings',
];

foreach ($tables as $table) {
    fwrite(STDOUT, "  - Бэкап таблицы: $table\n");
    
    // Структура таблицы
    fwrite($fp, "-- Table: $table\n");
    fwrite($fp, "DROP TABLE IF EXISTS `$table`;\n");
    
    $createStmt = $pdo->query("SHOW CREATE TABLE `$table`")->fetch();
    fwrite($fp, $createStmt[1] . ";\n\n");
    
    // Данные таблицы
    $rows = $pdo->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
    
    if (!empty($rows)) {
        $columns = array_keys($rows[0]);
        $columnsList = implode('`, `', $columns);
        
        foreach ($rows as $row) {
            $values = array_map(function($v) use ($pdo) {
                return $v === null ? 'NULL' : $pdo->quote($v);
            }, array_values($row));
            
            fwrite($fp, "INSERT INTO `$table` (`$columnsList`) VALUES (" . implode(', ', $values) . ");\n");
        }
        fwrite($fp, "\n");
    }
}

fwrite($fp, "SET FOREIGN_KEY_CHECKS = 1;\n");
fclose($fp);

$fileSize = filesize($backupFile);
$fileSizeMB = round($fileSize / 1024 / 1024, 2);

fwrite(STDOUT, "\n✓ Бэкап создан: $backupFile\n");
fwrite(STDOUT, "  Размер: $fileSizeMB МБ\n");

// Удаление старых бэкапов (старше 30 дней)
$files = glob($backupDir . '/backup_*.sql');
$now = time();
$deleted = 0;

foreach ($files as $file) {
    if (is_file($file) && ($now - filemtime($file)) > (30 * 24 * 60 * 60)) {
        unlink($file);
        $deleted++;
    }
}

if ($deleted > 0) {
    fwrite(STDOUT, "\nУдалено старых бэкапов: $deleted\n");
}
